const productCategories = [
  "Bags",
  "Clothing",
  "Electronics",
  "Books",
  "Furniture",
  "Home",
  "Beauty",
  "Toys",
  "Sports",
  "Jewelry",
  "Kitchenware",
  "Tech_Accessories",
  "Watches",
  "Home_Decor",
  "Pets",
  "Art",
  "Outdoor",
  "Stationery",
  "Shoes",
  "Eyewear",
  "Hair & Wigs",
  "Food & Groceries",
  "Drinks & Beverages",
  "Health & Wellness",
  "Baby & Kids",
  "Automobile Accessories",
  "Phones & Tablets",
  "Gaming",
  "Musical Instruments",
  "Office Supplies",
  "Handmade & Crafts",
  "Religious Items",
  "Skincare",
  "Perfumes",
  "Medical Supplies",
  "Agricultural Products",
  "Safety & Security",
  "Party & Events Supplies",
  "Industrial Equipment",
  "Fitness & Gym",
];

export default productCategories;
