const vendors = [
  {
    vendor_id: "1",
    storeName: "Perfumes World",
    storeTag: "perfumes_world",
    email: "perfumesworld@gmail.com",
    categories: ["Bags", "Clothing"],
    logo: "https://picsum.photos/id/21/3008/2008",
    banner: "https://picsum.photos/id/26/367/267",
    location: {
      state: "Oyo State",
      city: "Ibadan",
      country: "Nigeria",
    },
    joined: "February, 2025",
    socials: {
      instagram: "",
      twitter: "",
      whatsapp: "",
    },
    phone: "+2347037887923",
    acct: {
      number: "7037887923",
      bank: "PalmPay",
      name: "Olalekan Oladimeji Segun",
    },
    deliveryRange: ["Ibadan", "Oyo", "Lagos"],
    minPrice: 4000,
  },
  {
    vendor_id: "2",
    storeName: "Trendy Wears",
    storeTag: "trendy_wears",
    email: "trendywears@gmail.com",
    categories: ["Electronics", "Books"],
    logo: "https://picsum.photos/id/22/3008/2008",
    banner: "https://picsum.photos/id/27/367/267",
    location: {
      state: "Lagos State",
      city: "Lagos",
      country: "Nigeria",
    },
    joined: "March, 2025",
    socials: {
      instagram: "@trendywears",
      twitter: "@trendywears_ng",
      whatsapp: "+2348109876543",
    },
    phone: "+2348109876543",
    acct: {
      number: "1023456789",
      bank: "GTBank",
      name: "Adebayo Johnson",
    },
    deliveryRange: ["Lagos", "Ibadan"],
    minPrice: 7000,
  },
  {
    vendor_id: "3",
    storeName: "Gadget Hub",
    storeTag: "gadget_hub",
    email: "gadgethub@gmail.com",
    categories: ["Furniture", "Home"],
    logo: "https://picsum.photos/id/23/3008/2008",
    banner: "https://picsum.photos/id/28/367/267",
    location: {
      state: "Abuja",
      city: "Gwarinpa",
      country: "Nigeria",
    },
    joined: "January, 2025",
    socials: {
      instagram: "@gadgethub",
      twitter: "@gadgethub_ng",
      whatsapp: "+2348035678901",
    },
    phone: "+2348035678901",
    acct: {
      number: "2098765432",
      bank: "Zenith Bank",
      name: "Chinedu Okeke",
    },
    deliveryRange: ["Abuja", "Nationwide"],
    minPrice: 18000,
  },
  {
    vendor_id: "4",
    storeName: "Luxury Decor",
    storeTag: "luxury_decor",
    email: "luxurydecor@gmail.com",
    categories: ["Beauty", "Toys", "Clothing"],
    logo: "https://picsum.photos/id/24/3008/2008",
    banner: "https://picsum.photos/id/29/367/267",
    location: {
      state: "Rivers State",
      city: "Port Harcourt",
      country: "Nigeria",
    },
    joined: "May, 2025",
    socials: {
      instagram: "@luxurydecor",
      twitter: "@luxurydecor_ng",
      whatsapp: "+2348061234567",
    },
    phone: "+2348061234567",
    acct: {
      number: "3056789012",
      bank: "UBA",
      name: "Ngozi Amadi",
    },
    deliveryRange: ["Port Harcourt"],
    minPrice: 60000,
  },
  {
    vendor_id: "5",
    storeName: "Fit & Fab",
    storeTag: "fit_fab",
    email: "fitfab@gmail.com",
    categories: ["Sports", "Beauty"],
    logo: "https://picsum.photos/id/25/3008/2008",
    banner: "https://picsum.photos/id/30/367/267",
    location: {
      state: "Kano State",
      city: "Kano",
      country: "Nigeria",
    },
    joined: "April, 2025",
    socials: {
      instagram: "@fitfab",
      twitter: "@fitfab_ng",
      whatsapp: "+2348123456789",
    },
    phone: "+2348123456789",
    acct: {
      number: "4067890123",
      bank: "Access Bank",
      name: "Musa Ibrahim",
    },
    deliveryRange: ["Kano"],
    minPrice: 8000,
  },
  {
    vendor_id: "6",
    storeName: "Glitz Jewelry",
    storeTag: "glitz_jewelry",
    email: "glitzjewelry@gmail.com",
    categories: ["Jewelry", "Sports"],
    logo: "https://picsum.photos/id/26/3008/2008",
    banner: "https://picsum.photos/id/31/367/267",
    location: {
      state: "Osun State",
      city: "Osogbo",
      country: "Nigeria",
    },
    joined: "June, 2025",
    socials: {
      instagram: "@glitzjewelry",
      twitter: "@glitzjewelry_ng",
      whatsapp: "+2348156789012",
    },
    phone: "+2348156789012",
    acct: {
      number: "5078901234",
      bank: "First Bank",
      name: "Tolu Adebayo",
    },
    deliveryRange: ["Osun"],
    minPrice: 5000,
  },
  {
    vendor_id: "7",
    storeName: "Swift Electronics",
    storeTag: "swift_electronics",
    email: "swiftelectronics@gmail.com",
    categories: ["Books"],
    logo: "https://picsum.photos/id/27/3008/2008",
    banner: "https://picsum.photos/id/32/367/267",
    location: {
      state: "Edo State",
      city: "Benin City",
      country: "Nigeria",
    },
    joined: "July, 2025",
    socials: {
      instagram: "@swiftelec",
      twitter: "@swiftelec_ng",
      whatsapp: "+2348178901234",
    },
    phone: "+2348178901234",
    acct: {
      number: "6089012345",
      bank: "EcoBank",
      name: "Osagie Ehigiator",
    },
    deliveryRange: ["Benin"],
    minPrice: 20000,
  },
  {
    vendor_id: "8",
    storeName: "Fashion Avenue",
    storeTag: "fashion_avenue",
    email: "fashionavenue@gmail.com",
    categories: ["Jewelry"],
    logo: "https://picsum.photos/id/28/3008/2008",
    banner: "https://picsum.photos/id/33/367/267",
    location: {
      state: "Anambra State",
      city: "Awka",
      country: "Nigeria",
    },
    joined: "August, 2025",
    socials: {
      instagram: "@fashionavenue",
      twitter: "@fashionavenue_ng",
      whatsapp: "+2348189012345",
    },
    phone: "+2348189012345",
    acct: {
      number: "7090123456",
      bank: "Stanbic IBTC",
      name: "Chisom Nwankwo",
    },
    deliveryRange: ["Anambra"],
    minPrice: 14000,
  },
  {
    vendor_id: "9",
    storeName: "Mega Mart",
    storeTag: "mega_mart",
    email: "megamart@gmail.com",
    categories: ["Home"],
    logo: "https://picsum.photos/id/29/3008/2008",
    banner: "https://picsum.photos/id/34/367/267",
    location: {
      state: "Ogun State",
      city: "Abeokuta",
      country: "Nigeria",
    },
    joined: "September, 2025",
    socials: {
      instagram: "@megamart",
      twitter: "@megamart_ng",
      whatsapp: "+2348190123456",
    },
    phone: "+2348190123456",
    acct: {
      number: "8091234567",
      bank: "Fidelity Bank",
      name: "Babatunde Olawale",
    },
    deliveryRange: ["Ogun", "Lagos", "Ibadan"],
    minPrice: 24000,
  },
  {
    vendor_id: "10",
    storeName: "Beauty Haven",
    storeTag: "beauty_haven",
    email: "beautyhaven@gmail.com",
    categories: ["Toys"],
    logo: "https://picsum.photos/id/30/3008/2008",
    banner: "https://picsum.photos/id/35/367/267",
    location: {
      state: "Kaduna State",
      city: "Kaduna",
      country: "Nigeria",
    },
    joined: "October, 2025",
    socials: {
      instagram: "@beautyhaven",
      twitter: "@beautyhaven_ng",
      whatsapp: "+2348201234567",
    },
    phone: "+2348201234567",
    acct: {
      number: "9092345678",
      bank: "Union Bank",
      name: "Fatima Bello",
    },
    deliveryRange: ["Kaduna"],
    minPrice: 2500,
  },
  {
    vendor_id: "11",
    storeName: "Glow Essentials",
    storeTag: "glow_essentials",
    email: "glowessential@gmail.com",
    categories: ["Bags", "Jewelry", "Electronics", "Kitchenware"],
    logo: "https://picsum.photos/id/31/3008/2008",
    banner: "https://picsum.photos/id/36/367/267",
    location: {
      state: "Lagos State",
      city: "Ikeja",
      country: "Nigeria",
    },
    joined: "March, 2025",
    socials: {
      instagram: "@glowessentials",
      twitter: "@glow_essentials",
      whatsapp: "+2348109876543",
    },
    phone: "+2348109876543",
    acct: {
      number: "1012345678",
      bank: "Access Bank",
      name: "Aisha Mohammed",
    },
    deliveryRange: ["Lagos"],
    minPrice: 3000,
  },
  {
    vendor_id: "12",
    storeName: "Urban Styles",
    storeTag: "urban_styles",
    email: "urbanstyles@gmail.com",
    categories: ["Clothing", "Electronics", "Tech_Accessories", "Watches"],
    logo: "https://picsum.photos/id/32/3008/2008",
    banner: "https://picsum.photos/id/37/367/267",
    location: {
      state: "Abuja",
      city: "Garki",
      country: "Nigeria",
    },
    joined: "June, 2025",
    socials: {
      instagram: "@urbanstyles",
      twitter: "@urbanstyles_ng",
      whatsapp: "+2348123456789",
    },
    phone: "+2348123456789",
    acct: {
      number: "2023456789",
      bank: "GTBank",
      name: "Emeka Okoro",
    },
    deliveryRange: ["Abuja"],
    minPrice: 5000,
  },
  {
    vendor_id: "13",
    storeName: "Tech Haven",
    storeTag: "tech_haven",
    email: "techhaven@gmail.com",
    categories: ["Clothing", "Watches", "Home_Decor", "Pets"],
    logo: "https://picsum.photos/id/33/3008/2008",
    banner: "https://picsum.photos/id/38/367/267",
    location: {
      state: "Oyo State",
      city: "Ibadan",
      country: "Nigeria",
    },
    joined: "September, 2025",
    socials: {
      instagram: "@techhaven",
      twitter: "@techhaven_ng",
      whatsapp: "+2348156789012",
    },
    phone: "+2348156789012",
    acct: {
      number: "3034567890",
      bank: "First Bank",
      name: "Bola Adeyemi",
    },
    deliveryRange: ["Oyo"],
    minPrice: 8000,
  },
  {
    vendor_id: "14",
    storeName: "Foodies Hub",
    storeTag: "foodies_hub",
    email: "foodieshub@gmail.com",
    categories: ["Home_Decor", "Pets", "Beauty", "Art"],
    logo: "https://picsum.photos/id/34/3008/2008",
    banner: "https://picsum.photos/id/39/367/267",
    location: {
      state: "Rivers State",
      city: "Port Harcourt",
      country: "Nigeria",
    },
    joined: "November, 2025",
    socials: {
      instagram: "@foodieshub",
      twitter: "@foodieshub_ng",
      whatsapp: "+2348178901234",
    },
    phone: "+2348178901234",
    acct: {
      number: "4045678901",
      bank: "Zenith Bank",
      name: "Chidimma Okafor",
    },
    deliveryRange: ["Rivers"],
    minPrice: 2000,
  },
  {
    vendor_id: "15",
    storeName: "Auto Pro",
    storeTag: "auto_pro",
    email: "autopro@gmail.com",
    categories: ["Beauty", "Art", "Jewelry"],
    logo: "https://picsum.photos/id/40/3008/2008",
    banner: "https://picsum.photos/id/41/367/267",
    location: {
      state: "Kano State",
      city: "Kano",
      country: "Nigeria",
    },
    joined: "January, 2026",
    socials: {
      instagram: "@autopro",
      twitter: "@autopro_ng",
      whatsapp: "+2348067890123",
    },
    phone: "+2348067890123",
    acct: {
      number: "5056789012",
      bank: "UBA",
      name: "Musa Abdullahi",
    },
    deliveryRange: ["Kano"],
    minPrice: 10000,
  },
  {
    vendor_id: "16",
    storeName: "Green Farm",
    storeTag: "green_farm",
    email: "greenfarm@gmail.com",
    categories: ["Sports", "Outdoor"],
    logo: "https://picsum.photos/id/42/3008/2008",
    banner: "https://picsum.photos/id/43/367/267",
    location: {
      state: "Benue State",
      city: "Makurdi",
      country: "Nigeria",
    },
    joined: "April, 2026",
    socials: {
      instagram: "@greenfarm",
      twitter: "@greenfarm_ng",
      whatsapp: "+2348090123456",
    },
    phone: "+2348090123456",
    acct: {
      number: "6067890123",
      bank: "EcoBank",
      name: "John Odeh",
    },
    deliveryRange: ["Benue"],
    minPrice: 4000,
  },
  {
    vendor_id: "17",
    storeName: "Elite Shoes",
    storeTag: "elite_shoes",
    email: "eliteshoes@gmail.com",
    categories: ["Books", "Stationery"],
    logo: "https://picsum.photos/id/44/3008/2008",
    banner: "https://picsum.photos/id/45/367/267",
    location: {
      state: "Enugu State",
      city: "Enugu",
      country: "Nigeria",
    },
    joined: "May, 2026",
    socials: {
      instagram: "@eliteshoes",
      twitter: "@eliteshoes_ng",
      whatsapp: "+2348071234567",
    },
    phone: "+2348071234567",
    acct: {
      number: "7078901234",
      bank: "Stanbic IBTC",
      name: "Ifeanyi Udeh",
    },
    deliveryRange: ["Enugu"],
    minPrice: 7000,
  },
  {
    vendor_id: "18",
    storeName: "Smart Home Tech",
    storeTag: "smart_home",
    email: "smarthometech@gmail.com",
    categories: ["Furniture", "Shoes"],
    logo: "https://picsum.photos/id/46/3008/2008",
    banner: "https://picsum.photos/id/47/367/267",
    location: {
      state: "Osun State",
      city: "Osogbo",
      country: "Nigeria",
    },
    joined: "July, 2026",
    socials: {
      instagram: "@smarthome",
      twitter: "@smarthome_ng",
      whatsapp: "+2348056789012",
    },
    phone: "+2348056789012",
    acct: {
      number: "8089012345",
      bank: "Fidelity Bank",
      name: "David Akinyemi",
    },
    deliveryRange: ["Osun"],
    minPrice: 6000,
  },
  {
    vendor_id: "19",
    storeName: "Royal Furniture",
    storeTag: "royal_furniture",
    email: "royalfurniture@gmail.com",
    categories: ["Kitchenware", "Bags", "Tech_Accessories"],
    logo: "https://picsum.photos/id/48/3008/2008",
    banner: "https://picsum.photos/id/49/367/267",
    location: {
      state: "Ekiti State",
      city: "Ado-Ekiti",
      country: "Nigeria",
    },
    joined: "August, 2026",
    socials: {
      instagram: "@royalfurniture",
      twitter: "@royalfurniture_ng",
      whatsapp: "+2348081234567",
    },
    phone: "+2348081234567",
    acct: {
      number: "9090123456",
      bank: "Union Bank",
      name: "Kunle Adewale",
    },
    deliveryRange: ["Ekiti"],
    minPrice: 15000,
  },
];

export default vendors;
